### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Special-Base** [Bkm016/TabooMenu#18]
[17:24:13 ERROR]: Could not pass event InventoryClickEvent to TabooMenu v2.63
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
        at me.skymc.taboomenu.display.Icon.executeCommand(Icon.java:126) ~[?:?]
        at me.skymc.taboomenu.display.Icon.onClick(Icon.java:114) ~[?:?]
        at me.skymc.taboomenu.listener.ListenerInventory.onClick(ListenerInventory.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor633.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[17:24:14 ERROR]: Could not pass event InventoryClickEvent to TabooMenu v2.63
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_201]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_201]
        at me.skymc.taboomenu.display.Icon.executeCommand(Icon.java:126) ~[?:?]
        at me.skymc.taboomenu.display.Icon.onClick(Icon.java:114) ~[?:?]
        at me.skymc.taboomenu.listener.ListenerInventory.onClick(ListenerInventory.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor633.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[Paper-1.14.4-b154.jar:git-Paper-153]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Arasple** [comment]
will be fixed
