### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by luobochuanqi** [Bkm016/TabooMenu#24]
[15:48:31] [Server thread/ERROR]: Error occurred while enabling TabooMenu v2.63 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @4a50b70a
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at me.skymc.taboomenu.handler.itemsource.ItemSourceHandler.addToPath(ItemSourceHandler.java:52) ~[TabooMenu.jar:?]
	at me.skymc.taboomenu.handler.itemsource.ItemSourceHandler.addToPath(ItemSourceHandler.java:61) ~[TabooMenu.jar:?]
	at me.skymc.taboomenu.handler.itemsource.ItemSourceHandler.inst(ItemSourceHandler.java:34) ~[TabooMenu.jar:?]
	at me.skymc.taboomenu.TabooMenu.onEnable(TabooMenu.java:71) ~[TabooMenu.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-51]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-51]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Airplane-51]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Airplane-51]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Airplane-51]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:727) ~[patched_1.17.1.jar:git-Airplane-51]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:328) ~[patched_1.17.1.jar:git-Airplane-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Airplane-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Airplane-51]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by luobochuanqi** [comment]
忘记看版本了，希望会支持更高版本
