### ISSUE TITLE
TabooMenu加载菜单时出错

### ISSUE THREAD

**Issue by shaokeyibb** [Bkm016/TabooMenu#5]
[00:02:29 INFO]: shaokeyibb issued server command: /taboomenu reload
[00:02:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'taboomenu' in plugin TabooMenu v2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1587]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1587]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1587]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1587]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1587]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at me.skymc.taboomenu.serialize.IconSerializer.loadIconFromMap(IconSerializer.java:142) ~[?:?]
        at me.skymc.taboomenu.serialize.MenuSerializer.loadMenuIcons(MenuSerializer.java:93) ~[?:?]
        at me.skymc.taboomenu.serialize.MenuSerializer.loadMenu(MenuSerializer.java:50) ~[?:?]
        at me.skymc.taboomenu.TabooMenu.load(TabooMenu.java:148) ~[?:?]
        at me.skymc.taboomenu.TabooMenuCommand.reloadCommand(TabooMenuCommand.java:110) ~[?:?]
        at me.skymc.taboomenu.TabooMenuCommand.onCommand(TabooMenuCommand.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1587]
        ... 15 more

**Comment by Createcc** [comment]
我paper b1615 1.12.2也是报错

**Comment by Arasple** [comment]
尝试使用最新版本
